[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["node_modules", "lib"]
test = "contracts/test"
script = "contracts/script"
solc = "0.8.20"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
localhost = "http://localhost:8545"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }